### PR TITLE
add html generator

### PR DESCRIPTION
**Pull request by rocketOC**
- analyze.py will now output the results to output.json.
- Running `python3 generate_html.py from python-seo-analyze/seoanalyzer` will serve the output from your local machine.
- The page is nice and plain for the first iteration

### CODE REVIEW

**Comment by sethblack** [comment]
@rocketOC Sweeet! Thank you for this.

How would you feel about swapping out the Flask dep with Jinja2 and moving that all to a third parameter [html|json]? Then either way you'll get your output to stdout so you can pipe it to whatever file you'd like. I know a lot of people use this from the depths of their network and would rather not serve web pages directly from the analyzer. Also this new functionality wouldn't be available if installed from pip, which is how most people get it AFAIK.

I like the simplicity of the design. Wanna slap in the CDN Bootstrap4 or Foundation and see how that looks?

**Comment by rocketOC** [comment]
- I removed flask and implemented jinja2
- added third [json|html] parameter
- uses bootstrap (needs improvement)
- sortable tables (click th)
- example: https://pastebin.com/hV9crmMH

> Also this new functionality wouldn't be available if installed from pip

I don't know if this commit is any better off with regard to the comment above. I didn't/don't understand the complication. I haven't prepared a package for pip downloading before.

**Comment by sethblack** [comment]
Oh man, I love it @rocketOC! This is much better. Thank you.

Yeah, the notices shove the content out horizontally and there are some tags that need to be escaped (such as img tags, it actually tries to render the image hehe). Also, could you please convert the keyword analysis into inline pills eg: <span>Keyword (count)</span>. That should free up some space and still keep it legible. Your thoughts?

Regarding the pip setup - yes, you figured it out. You just generally have to be mindful of adding extra dependencies that you're not 100% using (I hate the dep for nltk and will probably strip it out in a future version), and for command line tools try to keep everything limited to stdin/stdout or add a --file arg (also thinking about moving the positional args to argparse).

tyty!

**Comment by rocketOC** [comment]
Np. Argparse will allow the user to generate the html without the sitemap, so I think that is a good thing.

- Do you have a site that I can test the escaping on?
- Are you imagining the count as a badge in each of the inline keyword pills? 
- It sounds to me like you want to do 1 with the keywords. Is that right? I think the pills are a typical of a web layout, but unfriendly for copying the table into a spreadsheet. You know the users better than I do, so it's your call. Do you see it expanding into a page v keyword table in the future?

```
1.   [keyword1 (count1)][keyword2 (count2)][keyword3 (count3)]
```
```
2.   [keyword1 (count1)]
     [keyword2 (count2)]
     [keyword3 (count3)]
```
- For the notice width issue:
-- We could remove the site root from the page's url if it were passed in the output dictionary
-- Wrap the page url
-- Have the notices button hide the social counts when it shows the notices
-- Have the notices expand into a modal or row beneath the first row
-- Make a second header with the social site (facebook) merged across columns to save width
-- Change the header text for social into the icons

**Comment by sethblack** [comment]
Cool, thank you!

> Do you have a site that I can test the escaping on?

Yes: http://www.sethserver.com/ will break it (and it's a single page, so it crawls quickly)

> Are you imagining the count as a badge in each of the inline keyword pills? ...

Correct. Hmm. Also, good point about not being able to copy-paste it into a spreadsheet. I say we stick with idea 2 (the way you have it now); it seems more logical.

Re: Notice width issue I like "Have the notices expand into a modal or row beneath the first row".

tyty!

**Comment by rocketOC** [comment]
@sethblack 
- I moved the error messages to new rows following each primary row in the pages table
- Each row in the page table is now independently collapsable
- The cost of moving the error messages was to give up sorting on the page table (for now). It was a major improvement for readability. I chose not to do a modal because ctrl-f wouldn't work on the error messages. The second line is still not great for spreadsheet pasters, but maybe a more compatible export is the way to go if the users demand it.
- Error messages should now be escaped
- The page table running off the right side of the page is no longer an issue
- The keyword table is the same, as discussed.
- The bootstrap glyphicons were not loading from the cdn, so for now it is using google icons.
- It would be nice to trim out the jinja2 generated html whitespace in the future.

**Comment by sethblack** [comment]
This is great @rocketOC. I'm super happy with this work! Much appreciated.

**Pull request merged**
